service:
  name: image-diff
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs12.x

functions:
  diff:
    handler: handler.diff
    events:
      - http:
          method: post
          path: diff

custom:
  apigwBinary:
    types: #list of mime-types
      - 'multipart/form-data'
      - 'application/x-www-form-urlencoded'
      - 'image/png'
